org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m
android.useAndroidX=true
android.enableJetifier=true
# Esto fuerza a Gradle a usar el JDK 17
org.gradle.java.home=/usr/lib/jvm/java-17-openjdk
# Desactiva validaciones que rompen en Arch
android.experimental.privatizeResourceNamespacing=false
android.nonTransitiveRClass=false
